### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#1]
The documentation for turboPy is currently a mess (my bad!) and needs to be cleaned up, created where missing, and completed. This will involve using docstrings using the [numpydoc format](https://numpydoc.readthedocs.io/en/latest/format.html).

Docstrings need to be added for:
- [x] The module
- [x] The classes
- [x] The class methods

This should tie into the documentation effort mentioned in #2, and will enable automatic creation of much of the documentation that will end up on [readthedocs](https://readthedocs.org/projects/turbopy/).

**Comment by padamson** [comment]
Fixed link to #2 in this fork.

**Comment by arichar6** [comment]
I created a new branch, [dev-documentation](https://github.com/NRL-Plasma-Physics-Division/turbopy/tree/dev-documentation), where we can start working on the documentation. 

I'm not sure if the is the best way to proceed, but I'll start a WIP pull request, to give us a place to go to see how the documentation effort is progressing.

**Comment by padamson** [comment]
@arichar6 what do you think of this approach of creating "sub-issues" and "sub-PRs" for this issue? Makes it easier for everyone to assign themselves smaller parts of the problem a bit at a time. See #18 and #17 . Idea is for sub-PR to merge into dev-documentation.

**Comment by padamson** [comment]
I'm starting to think we just need a `dev` branch for all development (code, tests, and documentation). We shouldn't be developing documentation and tests on a stale branch.

**Comment by padamson** [comment]
In a way, `main` here is a development branch for turbopy that's in your personal github.

**Comment by padamson** [comment]
Or, when developing documentation, we could branch from `main` and merge into `dev-documentation`. That could get messy, though.

**Comment by arichar6** [comment]
I was planning to just merge any changes from `main` back into `dev-documentation` as necessary. It could get messy, but at least for documentation and testing, the changes should be happening to (mostly) separate files. So the merges should be pretty clean. I'm open to changes, though.

**Comment by arichar6** [comment]
Also,  I've been treating this repo as the "real" turbopy, and have started using my personal fork as my own dev space. I know it's a bit backwards, since turbopy started in my account. I'll do my best to have my `main` branch track with the `main` branch here.

**Comment by arichar6** [comment]
So, it looks to me that there is now documentation in the code. Some docstrings might be a bit short, and some edits probably still should happen, but I think the spirit of this issue is satisfied. 

So, I'm closing this issue. If you find things in the docs that need to change, please open another issue, and address it with it's own PR.

Thanks to everyone who helped get this done! 🎉
