### ISSUE TITLE
Add __str__ and __repr__ methods to all objects

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#13]
`__repr__` is a built-in function used to compute the “official” string representation of an object (it is "unambiguous"), while `__str__` is a built-in function that computes the “informal” string representation of an object.

See:
- RealPython: [`__repr__` vs `__str__`](https://realpython.com/lessons/__repr__-vs-__str__/).
- [`object.__repr__(self)`](https://docs.python.org/3/reference/datamodel.html?highlight=__repr__#object.__repr__)
- [`object.__str__(self)`](https://docs.python.org/3/reference/datamodel.html?highlight=__repr__#object.__str__)

We should consider adding `__repr__` and possibly `__str__` methods to all objects in turboPy.

**Comment by padamson** [comment]
"Minimal" `__repr__` implementation for a class:

```Python
  def __repr__(self):
    return '{self.__class__.__name__}({self.attribute1}, {self.attribute2}, ...})'.format(self=self)
```

**Comment by arichar6** [comment]
I think that before we add these methods to classes in turboPy, we should check what `repr()` and `str()` return for the turboPy classes. But I agree that this is something that would be good to think about. Having `__repr__` return more detailed information is extremely helpful when trying to debug code.

**Comment by arichar6** [comment]
I do think it's a good idea to add these methods where appropriate. However, I don't think this is high enough priority to work on right now. So I'm removing this from the testing milestone.

**Comment by arichar6** [comment]
Thanks @OwenGrannis 🎉
