### ISSUE TITLE
Update README to include `pip install turbopy` 

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#132]
The readme file currently describes how to create a conda env, and use pip to install the source code in "editable" mode within the environment.

Now that turboPy is available in PyPI, you can also just issue the command `pip install turbopy`. Information about how to do this should be in the readme. 

Perhaps a bit of reorganization of the readme is in order as well, where the old "install" method is moved into a "dev" section, and the PyPI stuff is in the main section.

**Comment by AOstenfeld** [comment]
What does the pip install turbopy replace in the current readme?

**Comment by arichar6** [comment]
Thanks @AOstenfeld!
