### ISSUE TITLE
Create tests for turbopy

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#14]
TurboPy currently lacks tests. We need unit tests and integration tests.

- [x] Add folder for tests
- [x] Create tests for the code
- [x] Check test coverage
- [x] Make sure tests are run as part of CI pipeline

**Comment by padamson** [comment]
#92 took care of 3rd item on list

**Comment by padamson** [comment]
Should we say complete at 90% test coverage?

**Comment by arichar6** [comment]
I'd say that we need to get the code coverage up some more. Looking at the report on codecov.io, the main offender is computetools.py. I'm not really sure what to do about that, as most of the code there is in the finite difference helper class. While it would be nice to have test of that code, the code itself is in pretty rough shape.

The other place where we can improve the test coverage is in diagnostics.py. I'm adding an issue now to write a test for the FieldDiagnostic class, which should bring the coverage for that file up substantially.

**Comment by arichar6** [comment]
Regarding computetools.py, I think if we have test of the BorisPush class and the Interpolators class, I'd be satisfied for now. I'll go make issues for those classes.

**Comment by arichar6** [comment]
Completed with #105
