### ISSUE TITLE
Add functionality for writing the CSV buffer to file durning a simulation

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#145]
Currently, the only time that a CSV diagnostic writes its buffer to file is at the end:
https://github.com/NRL-Plasma-Physics-Division/turbopy/blob/165a006ad9ea776e775ef5d823791549b7a53ca5/turbopy/diagnostics.py#L55

It would be useful to have an option to write the buffer to file at some interval, so that it would be easier to monitor the progress of long-running simulations.

**Comment by arichar6** [comment]
Thanks for working on this, and for your patience with me getting back to you.

I have some comments, and the code will probably have to be rearranged some from what you wrote. I'll try and put the comments in a review.

**Comment by arichar6** [comment]
So I think I should clean up the `OutputUtility` functionality a bit before we continue with this. It should make the code more organized, and easier to extend. I'd say pause on this for a bit until I get that in place.

**Comment by arichar6** [comment]
@AOstenfeld see #150 for some ideas that I'm trying for refactoring the way that Diagnostics + OutputUtilities work. I'd appreciate thoughts/comments on that code. It should make your effort easier.

**Comment by AOstenfeld** [comment]
Sounds good. I'll check it out.

**Comment by arichar6** [comment]
See my comment on #148 for some new ideas I had for this.
