### ISSUE TITLE
Create pdf version of the documentation

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#16]
ReadTheDocs will use sphinx to automatically create a pdf version of the documentation. 

This is great. But some stuff might look odd in the pdf version, which looked fine in the html version.

This issue is just to remind us to check the pdf version, and make sure it looks good.

**Comment by arichar6** [comment]
Related to #1

**Comment by padamson** [comment]
I think we can have the pdf emailed to us periodically through github actions. [Send mailer](https://github.com/marketplace/actions/send-mailer) supports attachment.

**Comment by arichar6** [comment]
Interesting... I should spend some time learning more about github actions

**Comment by arichar6** [comment]
Just checked the PDF generated at ReadTheDocs. It actually seems to be working fine... not sure why it wasn't before.
