### ISSUE TITLE
 Where should we build and test turboPy now that building on travis-ci.org is ceased?

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#177]
**Discussion Topic**: Where should we build and test turboPy now that building on travis-ci.org is ceased?

Possible options:
- Go to travis-ci.com. Building is still free for open source projects. 
- One solution that works for open source and non-open source (private) repos.

**Comment by arichar6** [comment]
One possibility could be [GitHub Actions](https://docs.github.com/en/actions). I think it might have the same limitations for private repos, though.

**Comment by arichar6** [comment]
I've switched over to travis-ci.com. That seemed like the easiest thing to do for right now.

I think the build badge on the readme is pointing to the .org site, though. That still needs to be fixed.
