### ISSUE TITLE
Implement baseline Continuous Integration

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#2]
- [x] add some unit tests
- [x] connect to TravisCI
- [x] verify triggering of automated tests
- [x] add TravisCI 'build' badge to README
- [x] add CONTRIBUTING w/info on testing
- [x] initialize documentation with Sphinx
- [x] add minimum set of documentation
- [x] connect to readthedocs.org
- [x] verify triggering of automated update to docs/docstrings
- [x] update CONTRIBUTING w/info on docs

**Comment by padamson** [comment]
@NRL-Plasma-Physics-Division/mentors I believe mentor work on this issue is complete

**Comment by arichar6** [comment]
Also, we need to make sure that when a test fails, the build fails.

**Comment by arichar6** [comment]
I've connected this repo to readthedocs. Finally got it working!

While the docs do build, it gives me a message which recommends using a .readthedocs.yml [configuration file](https://docs.readthedocs.io/page/config-file/v2.html). Seems like that is probably a good idea.

**Comment by padamson** [comment]
Bump...I'll work on making build fail when tests fail. We just got burned by changing name of a class and integration tests failed, but build did not fail. 

Also, would be nice to have a test coverage badge.

**Comment by padamson** [comment]
See #59 ...build should fail when tests fail

**Comment by GarethTMorgan** [comment]
Adding the Travis CI build badge seems pretty easy for someone who has the permissions. [This](http://www.codeblocq.com/2016/04/Add-a-build-passing-badge-to-your-github-repository/) looks like a pretty simple guide. CONTRIBUTING has been made and includes stuff about testing so I think that checkbox can also be marked off. And I would say that we have 'minimum' documentation pretty much in the bag haha.

**Comment by arichar6** [comment]
Here's the markdown for the Travis CI badge:
[![Build Status](https://travis-ci.org/NRL-Plasma-Physics-Division/turbopy.svg?branch=main)](https://travis-ci.org/NRL-Plasma-Physics-Division/turbopy)

`[![Build Status](https://travis-ci.org/NRL-Plasma-Physics-Division/turbopy.svg?branch=main)](https://travis-ci.org/NRL-Plasma-Physics-Division/turbopy)`

If you can do a PR to add that to the readme, then I'll merge.

**Comment by arichar6** [comment]
I think with the update #90 to add the TravisCI badge to the readme, we have completed the work described in this issue.

Thanks for all the contributions everyone! 🎉
