### ISSUE TITLE
New Labels

### ISSUE THREAD

**Issue by GarethTMorgan** [NRL-Plasma-Physics-Division/turbopy#21]
Please add custom labels below that you think belong on the turbopy repo. An admin will review suggestions and add labels that seem useful.

Initial List:
* Governance

**Comment by arichar6** [comment]
Oops... I just added a "tests" label... I probably should have suggested it here and discussed first!

Any thoughts on having a label called "tests"? At first I was going to call it "testing", but realized that if I did, it might look like someone was just "testing" the labeling system on GitHub. It seems like the meaning of  "tests" is more clear.

**Comment by padamson** [comment]
As BDFL you can add the tests label. ;)  I like it.

**Comment by GarethTMorgan** [comment]
Would it be possible to give interns the ability to apply labels to PR's and issues? I just noticed the PR I just sent should have the documentation label and I can't add it.

**Comment by arichar6** [comment]
I've updated permissions for the intern group. You should be able to add labels to PRs now.

**Comment by GarethTMorgan** [comment]
It seems that the labels we have are good for the moment. I'm going to go ahead and close this issue.
