### ISSUE TITLE
Update docstring for `CSVDiagnosticOutput` class

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#29]
In the docstring, the parameter `diagnostic_size` is listed as being of type `int`. It actually should be a tuple, which gives the size of the buffer. 

https://github.com/NRL-Plasma-Physics-Division/turbopy/blob/5722606c2dc5800aaa850af93e28bb1c90fc63af/turbopy/diagnostics.py#L23

As can be seen in the `append` function, the first axis of the buffer is the "time", and the second is the "space" (which can be just a single point). 
```python
def append(self, data):
    self.buffer[self.buffer_index, :] = data
    self.buffer_index += 1
```
So `diagnostic_size` is type (`int`, `int`), where the first is the number of time points, and the second is the number of spatial points.

**Comment by GarethTMorgan** [comment]
I can do this real quick.

**Comment by GarethTMorgan** [comment]
#31 Fulfilled this issue
