### ISSUE TITLE
Use `xarray.DataArray` class for shared data

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#33]
Currently, turboPy allows the sharing of any python object. This of course is the most useful if the object is mutable, so that different `PhysicsModules` can all store references to the same (changing) object.

I've recently started using [`xarray`](http://xarray.pydata.org/en/stable/), and its `DataArray` classes are very powerful. See [this commit to the example app](https://github.com/NRL-Plasma-Physics-Division/particle-in-field/commit/46f909d6556f7773e76afe3de25e56023d35bfa7) where the `numpy` array that was being used to store the electric field was changed to an `xarray.DataArray`. This allowed me to easily add metadata (like field name, units, grid coordinate name and units, etc).

It's worth discussing the possibility of using `xarray.DataArray` for the objects that `PhysicsModules` want to share with each other. This would open up a lot of possibilities, since it's easy to add custom metadata. E.g., this could make it easier to address #9 and #10.

Potential downsides would be adding another dependency (although xarray is becoming more common), and making it less flexible to share data.

Thoughts?

**Comment by padamson** [comment]
What about including uncertainty in input data?

When we characterize uncertainty in input data, we will have a PDF for each data point in our data set. Each point in the data set may have a common PDF, but they don't have to.

Proposals
=======

Proposal A
-----------

add a class (perhaps in computetools.py) for PDFs. There could be some "off the shelf" PDFs (Gaussian, Poisson, Uniform).

The app developer will instantiate a PDF for each one that is required, including parameters for the PDF.

In the data set, include metadata to point to the appropriate PDF. We could come up with an approach to use the same PDF for all points in the data set or define different PDFs for different points.

Proposal B
-----------

Create an InputData class to handle all aspects of creating input data. This might make it easier to tie to UQ tools for sampling PDFs and propagating uncertainty through turboPy apps. Also, this will standardize how input data (and metadata, including uncertainty) is defined.

**Comment by arichar6** [comment]
I've moved your post about uncertainties to a new issue. I like the idea, and think it deserves further thought.

I'm going to close this issue now, since I have successfully started using `xarray` for some turboPy projects, and there is nothing that needs to be done at the framework level to enable it.
