### ISSUE TITLE
create integration tests from apps

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#35]
**This comment is out of date...see below for updated proposal.**

To test many (if not all) of the features of turbopy, we need to have a range of turbopy apps included as fixtures in `tests/fixtures`.  This will provide the ability to do unit and integration testing covering all of the functionality of turbopy.

I propose the following:

- unit testing will be defined as testing only one turbopy class or method
- integration testing will be defined as testing more than one class or method and at least one interaction
- app fixtures will have a "long_name" and "short_name" (for example "particle_in_field" and "pif", respectively)
- app fixtures will be included in `tests/fixtures` in a sub-folder using the "long_name" of the app
- each app fixture will include a long_name.py file and a long_name.toml file
- each class definition and `Class.register` command will be a fixture named `short_name_class_name` or `short_name_class_name_register`, respectively.
- each app will have a `short_name_construct_simulation_from_toml` fixture to call the `construct_simulation_from_toml` on the `long_name.toml` file
- each app will have a `short_name_run` fixture to run the simulation

**Comment by padamson** [comment]
Contributes to #14

**Comment by padamson** [comment]
Rescoped issue to focus on integration testing after working through particle_in_field "integration test":

We can use simple apps for integration testing.
- integration testing will be defined as testing more than one class or method and at least one interaction
- app fixtures will have a "long_name" and "short_name" (for example "particle_in_field" and "pif", respectively)
- app fixtures and supporting files (e.g. .toml files, 'good' outputs) will be included in `tests/fixtures` in a sub-folder using the "long_name" of the app
- at a minimum, each integration test will include at least one fixture (`short_name_run`) to run the app and generate output for comparison to 'good' output

**Comment by padamson** [comment]
Also, perhaps we should separate unit and integration tests so we can run them separately and get coverage statistics for unit and integration tests. I like [this suggestion](https://stackoverflow.com/a/54899236) of having `unit` and `integration` directories under `tests`.

**Comment by arichar6** [comment]
Sounds good to me.

**Comment by arichar6** [comment]
Since we now have two different integration tests, I'm going to close this issue.
