### ISSUE TITLE
Add a Contribution guide

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#4]
We need to add a guide for contributors, to outline some of the development choices we are using. [This GitHub article](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) seems to be a good guide for creating the `CONTRIBUTING` file.

Some links that might be helpful to add could be:

- [15 rules for communicating at GitHub](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/)
- [GitHub Flow branching strategy](https://guides.github.com/introduction/flow/)

**Comment by arichar6** [comment]
This also needs to describe testing, as mentioned in #2 .

**Comment by padamson** [comment]
Description of documentation development should include the following:

`livereload`
------------

The very useful tool [`livereload`](https://livereload.readthedocs.io/en/latest/) for monitoring
changes in Sphinx documentation in real-time is included 
in the `turbopy` conda environment (`environment.yml` file). 
Here’s a simple script that detects changes in any `*.rst` files in `doc` or `*.py` files in `turbopy`,
rebuilds the Sphinx documentation, and starts a `livereload` server:

```python
#!/usr/bin/env python
from livereload import Server, shell
import formic

PATTERNS = ["doc/**.rst", "turbopy/**.py"]

SERVER = Server()
for filepath in formic.FileSet(include=PATTERNS):
    SERVER.watch(filepath, shell('make html', cwd='doc'))
SERVER.serve(root='doc/_build/html')
```

Run it inside the root directory of your clone of the `turbopy` repo, then open 
[http://localhost:5500/](http://localhost:5500/), and you can see any
documentation changes you are making in real time.

Sphinx cross-references
-----------------------

If you are having trouble determining the syntax for a Sphinx cross-reference (internal
or external), try the command-line tool [https://github.com/bskinn/sphobjinv](sphobjinv),
which is included in the `turbopy` conda environment (`environment.yml` file).

**Comment by arichar6** [comment]
I'd also like to start using [templates](https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests) for issues and pull requests. They should be described in the contribution guide.

**Comment by arichar6** [comment]
Also need to add info about the branch naming convention that we discussed.

**Comment by arichar6** [comment]
@littlewatkins I've assigned this to you. Feel free to tag some interns to help you with this 😄

**Comment by littlewatkins** [comment]
I made a first pass at a contributing markdown and noted in the pull request what should get added. Will continue adding tomorrow

**Comment by arichar6** [comment]
@NRL-Plasma-Physics-Division/interns The contributing guide still needs a section that describes documentation. It should note that we use `numpydoc` style docstrings, and that the documentation gets generated automatically at ReadTheDocs. 

Anyone interested in writing that section?

**Comment by littlewatkins** [comment]
@arichar6 I'll do that this afternoon

**Comment by arichar6** [comment]
I think that with #91, we have completed a minimal contributing doc. Might be nice to add the `livereload` stuff from Paul's comment above, but I don't that's necessary at this time.

**Comment by padamson** [comment]
I take back my suggestion on livereload. It's a useful tool for seeing real time edits to documentation, but there are many ways to do that...doesn't really belong in contributing.md IMHO.
