### ISSUE TITLE
Add turboPy paper preprint to README

### ISSUE THREAD

**Issue by AOstenfeld** [NRL-Plasma-Physics-Division/turbopy#47]
More of just a quality of life thing. I think it would be nice to add a link to the the preprint of the turboPy paper to the README instead of having it buried in turboPy-training. It might help with documentation and understanding the code.

**Comment by GarethTMorgan** [comment]
I think that sounds like a great idea, but we should probably check with an admin before moving any of the core documentation haha.

**Comment by arichar6** [comment]
Done!
