### ISSUE TITLE
Change name of `CVSDiagnosticOutput` class

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#49]
Problem
--------

https://github.com/NRL-Plasma-Physics-Division/turbopy/blob/ae9b1390aed9874a678c2fd0dfbc65e4e70978d0/turbopy/diagnostics.py#L10

The name of this class, `CVSDiagnosticOutput`, is somewhat misleading. It sounds like it should be a "diagnostic", in that it inherits from the `Diagnostic` base class. This is not the case. It does not inherit from `Diagnostic`. 

Rather, it is a "helper" class, in that it is meant to be used by "real" `Diagnostic` classes for writing data to files. This is achieved through composition.

Proposed Solution
-------------------
Refactor the code by changing the name of this class to something more descriptively accurate. Perhaps `CVSOutputHelper` or `CVSOutputUtility`?

Note that this is not a "utility" class or "helper" class as those are sometimes defined. Often this means that the class "contains just static methods, it is stateless and cannot be instantiated" ([from this link](https://www.vojtechruzicka.com/avoid-utility-classes/)). And this isn't true for this class.

What do you all think?

**Comment by GarethTMorgan** [comment]
CSVOutputProducer? CSVOutputService?

**Comment by padamson** [comment]
io modules? I've been eyeing [astropy's io module structure](https://github.com/astropy/astropy/tree/master/astropy/io) for nepc.  CSV is a type of ASCII.

**Comment by arichar6** [comment]
That astropy module looks pretty cool. I'll have to look into it some more...

I think I'll go with `CVSOutputUtility`, even thought it does more than just provide static methods. If anyone is confused, they can always refer to the source code, or the extensive documentation 😉

**Comment by arichar6** [comment]
I've added the "good first issue" tag, in case one of the @NRL-Plasma-Physics-Division/interns wants to take care of this refactoring. 

In order to close this issue, the class `CSVDiagnosticOutput` needs to be renamed to `CSVOutputUtility`. 

Note that this may break any code that uses this class, so you might also want to go to the "app" repos, and file bug reports there for any use of the "old" name that you find.

**Comment by GarethTMorgan** [comment]
I can go ahead and do this.

**Comment by GarethTMorgan** [comment]
just PR'd the change, am now making issues in app repo's.

**Comment by padamson** [comment]
There were a few other places to make the change. We didn't know because the build didn't fail when the tests failed. I'm fixing it in #59

**Comment by GarethTMorgan** [comment]
This issue might be ready to close.

**Comment by kphlips** [comment]
When I try to run particle_in_field, it says `cannot import name 'CSVDiagnosticOutput' from 'turbopy'`. Does the name need to be changed in particle_in _field as well?

**Comment by padamson** [comment]
I believe it is changed. When did you clone the repo?

**Comment by kphlips** [comment]
Yesterday, but I just realized it has now been fixed.

**Comment by GarethTMorgan** [comment]
The name of the class has been fixed in all instances. Closing this issue now.
