### ISSUE TITLE
Add tests for Grid class

### ISSUE THREAD

**Issue by AOstenfeld** [NRL-Plasma-Physics-Division/turbopy#57]
#### Create Test/s
*Adding tests for the methods in the grid class in core.py*

**Comment by AOstenfeld** [comment]
I don't think the template quite worked. Are those pound signs supposed to be visible?

**Comment by arichar6** [comment]
I think the template is missing a space between the pound signs and the text.

**Comment by AOstenfeld** [comment]
How do I single out test_core.py when running pytest? I've tried a bunch of different things, but it keeps running conftest.py and giving me an error.

**Comment by padamson** [comment]
In the root turbopy directory, just execute `pytest tests/test_core.py`.

**Comment by AOstenfeld** [comment]
It's still complaining about conftest. This is the message the terminal gives me.

ImportError while loading conftest 'C:\Users\Aaron\turboPy\turbopy\tests\conftest.py'.
tests\conftest.py:2: in <module>
    from fixtures.particle_in_field.particle_in_field import *
tests\fixtures\particle_in_field\particle_in_field.py:2: in <module>
    import xarray as xr
E   ModuleNotFoundError: No module named 'xarray'

I think the problem is just that it's running test/conftest.py for some reason.

**Comment by padamson** [comment]
@AOstenfeld are you running in the turbopy conda environment defined in environment.yml?  xarray was added to the environment when I added the particle_in_field integration test.

**Comment by AOstenfeld** [comment]
@padamson Yeah i figured it out

**Comment by AOstenfeld** [comment]
Could someone help me understand the create_interpolator method in the Grid class in core.py? These two lines are giving me problems.

i, = np.where((r0 - self.dr < self.r) & (self.r < r0 + self.dr))
assert (len(i) in [1, 2])

How does the comma after the i affect the code, and how does the where method work? I don't quite understand the documentation.

**Comment by AOstenfeld** [comment]
The above comment has been addressed
