### ISSUE TITLE
Add documentation to diagnostics.py 

### ISSUE THREAD

**Issue by carolinegsun** [NRL-Plasma-Physics-Division/turbopy#62]
Adding docstrings to the five classes in diagnostics.py

**Comment by GarethTMorgan** [comment]
@carolinegsun would you like some help with documentation? Let me know if/what you would like me to help/write.

**Comment by carolinegsun** [comment]
I'm working from the top classes to down (also going to be trying to write tests along with it)— PointDiagnostic and FieldDiagnostic are definitely more wieldy classes, so I think I'll try to tackle those all at once, but if you want to take a look at GridDiagnostic or ClockDiagnostic, that would be lovely! Just let me know :)

**Comment by GarethTMorgan** [comment]
I can work from the bottom up then. Starting on ClockDiagnostic right now. I'll let you know when I'm moving on to GridDiagnostic so so don't have any merge conflicts.

**Comment by GarethTMorgan** [comment]
Just PR'd the documentation for the ClockDiagnostic class. @carolinegsun would you like me to do the GridDiagnostic class as well since it's so similar?

**Comment by carolinegsun** [comment]
Sounds good! Do you know if it's possible for me "append" onto your PR later to add the documentation for the other 2 classes later?

**Comment by GarethTMorgan** [comment]
I had this same issue with the contributing file with Darryl. I think we decided that the simplest way would be to have you push to my dev branch on my personal repo. I'm also pretty sure we decided that it wasn't worth it. I think that just making a separate PR is the best way to do it 👍

**Comment by GarethTMorgan** [comment]
Just pushed the GridDiagnostic class documentation to my previous PR. Let me know if there's anything else I can do to help.

**Comment by carolinegsun** [comment]
Thanks so much! I should have the rest of the documentation up by end of day, latest.  :relaxed:

**Comment by GarethTMorgan** [comment]
No problem!

**Comment by arichar6** [comment]
Yep. Separate PRs is the way to go. 

Looking forward to the contributions!
