### ISSUE TITLE
Should we have team-wide issue/PR templates? 

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#64]
It seems like our issue/PR templates could be standardized across all of our repositories.  Should we start a "templates" repo and make changes to templates there and then copy them into each team repo when they change?

Reference #41

**Comment by arichar6** [comment]
That sounds like a pretty good idea. I'd also like to spend a bit of time polishing up the templates. Did you see the links I posted with template ideas? There are some really nice ones out there...

**Comment by padamson** [comment]
Yes, I skimmed them and agree there are some good examples, but need to go back and look more closely to see what we would want to adopt.

**Comment by padamson** [comment]
I actually think the answer to this question is 'no' for now. If someone sees a good template in use somewhere, they can bring it to any repo. Also, each repo is a little different so maybe templates need to be tailored.  Having a repo to manage templates is probably a bad idea unless we find we are managing many repos that should have identical templates.

I propose to close this with 'no.'
