### ISSUE TITLE
Add Documentation to Abstract Methods? 

### ISSUE THREAD

**Issue by GarethTMorgan** [NRL-Plasma-Physics-Division/turbopy#66]
**Question**
Should we be adding any sort of documentation to abstract methods like the "_factory_type_name" and "_registry" in the DynamicFactory class in core.py? I notice that there is no documentation in place and was wondering if that was by design.

**Comment by padamson** [comment]
I think for these private methods, it's good to just have a summary and perhaps an extended summary. That seems to be the approach taken in numpy.
