### ISSUE TITLE
Do we need `dev` and `non-dev` versions of the conda environment?

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#7]
Should we have two different conda environments for developing apps within the turbopy development environment vs developing turbopy itself?  For example, `livereload` would be in `turbopy-dev` but not in `turbopy`.

**Comment by GarethTMorgan** [comment]
Just to loop back to this issue. I guess I don't really understand why we would need two conda environments. Wouldn't it make sense to have one conda env just to sync development across apps and core?

**Comment by arichar6** [comment]
That's a good question. I think the point is that if there are any packages needed only for development on the core framework, they should go in the `turbopy-dev` environment, but not the `turbopy` environment. E.g. packages like `livereload` and `sphinx` are needed for development, but not by someone who just wants to use the framework.

Perhaps another way to get at what you are asking is "do we even need the 'non-dev' version of the environment?"

That is an interesting question. If we get to the point where the framework is on pypi and can be installed via `pip install turbopy` or `conda install turbopy`, then I don't really see a need for a "non-dev" conda environment. All of the prerequisites would be installed by the package manager (`pip` or `conda` as the case may be).

**Comment by padamson** [comment]
Very good point @arichar6. I'd support just thinking of the turbopy conda environment as the conda environment required for developing turbopy and turbopy apps. (I'll use this approach with nepc, too.)

**Comment by arichar6** [comment]
Ok. For now we will treat the `turbopy` conda environment as the "development version". At some point, we will have to figure out how package turbopy up for installation via a package manager. That will take care of the "non-dev" dependancies.
