### ISSUE TITLE
Unit test naming convention 

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#70]
**Discussion Topic**: Should we have a naming convention for unit tests, and if so, what should it be?

I believe we need a naming convention for unit tests. There are many reasons for this:

- easier to decipher what is happening when a test fails
- forces test developer to think about exactly what they are testing for when they write a test
- helps with organization to make sure we are writing all of the tests that we need

See [this SO thread](https://stackoverflow.com/questions/155436/unit-test-naming-best-practices) for some good thoughts. I like the **"Should"** naming convention.

**Comment by arichar6** [comment]
I like where you are going with this. I'll think about it.

**Comment by AOstenfeld** [comment]
I like the "Should" convention as well. Would it be okay of I started using it to write tests? I can just change the function names later if it doesn't work out.

**Comment by AOstenfeld** [comment]
I just realized that whatever we write will look different than the examples because of python's conventions. I was thinking a test might look something like this (based on the "Update 4 years later" section): test_init_should_create_class_instance_when_called()

**Comment by arichar6** [comment]
I like your example `test_init_should_create_class_instance_when_called()`. And yes, we can totally just change the name later if we want to.
