### ISSUE TITLE
Add tests to Simulation class 

### ISSUE THREAD

**Issue by AOstenfeld** [NRL-Plasma-Physics-Division/turbopy#73]
**Create Test/s**
*Adding tests to the methods in the Simulation class in core.py*

**Comment by AOstenfeld** [comment]
Actually I'm going to hold off working on this until the other tests are merged so I can work with the newest version of the test_core.py file.

**Comment by arichar6** [comment]
The `[WIP]` notation in the title is for pull requests, not issues.

**Comment by AOstenfeld** [comment]
oh

**Comment by padamson** [comment]
And we are moving away from [WIP] in the title of PRs and just using the "draft" PR feature. If you make your PR draft, then an admin cannot merge it.

**Comment by arichar6** [comment]
Completed with #89 

Thanks @AOstenfeld!
