### ISSUE TITLE
Are lines 305-313 formatted correctly in core.py?

### ISSUE THREAD

**Issue by GarethTMorgan** [NRL-Plasma-Physics-Division/turbopy#75]
**Question**
It seems to not be formatted correctly, was wondering if this needs to be changed.

**Comment by arichar6** [comment]
Short answer: no, they are not.
Longer answer: The docstring for `PhysicsModule` that you are talking about is a really just a barebones documentation placeholder. It should definitely be changed, to better conform to the style of documentation that we are trying to write.

**Comment by arichar6** [comment]
Please open an issue for the `PhysicsModule` class docstring. Then close this issue.
