### ISSUE TITLE
Finish documentation for Diagnostics, ComputeTools, and PhysicsModule in core.py 

### ISSUE THREAD

**Issue by gracetangg** [NRL-Plasma-Physics-Division/turbopy#76]
**Create Documentation**
*For what section of code is documentation to be written for?*
Finish documenting the attributes and parameters in the Diagnostics ComputeTools and PhysicsModule classes in core.py

**Comment by GarethTMorgan** [comment]
You beat me to it haha. Guess that's what I get for checking my email.

**Comment by gracetangg** [comment]
@GarethTMorgan LOL do you want to help me with one of them?

**Comment by GarethTMorgan** [comment]
I can if you would like me to! Let me know which class you would like me to work on if you want the assistance 👍

**Comment by carolinegsun** [comment]
me too! is there anything i could do to help?

**Comment by GarethTMorgan** [comment]
@carolinegsun do you have a preference as to which class you do?

**Comment by carolinegsun** [comment]
Was just going to ask you LOL! Fine with either :)

**Comment by GarethTMorgan** [comment]
I can do Diagnostics if you're okay with doing PhysicsModule.

**Comment by carolinegsun** [comment]
Sounds good!

**Comment by gracetangg** [comment]
do any of y'all know how i should document 
`_factory_type_name = "Compute Tool"` and ` _registry = {}`
are they just constants do you think?

**Comment by GarethTMorgan** [comment]
Pretty sure `_factory_type_name` is actually just a constant but I'm not so sure about the registry. @arichar6 any thoughts?

**Comment by GarethTMorgan** [comment]
Does anyone know whether the class attributes in `Diagnostics` are documented in a different section as the instance attributes in the dunder init?

**Comment by gracetangg** [comment]
I have the same question, I think the factory name would be a constant though since it doesn't change.

**Comment by GarethTMorgan** [comment]
Maybe, but I don't know enough to speak on it lol.

**Comment by arichar6** [comment]
> Pretty sure `_factory_type_name` is actually just a constant but I'm not so sure about the registry. @arichar6 any thoughts?

`_factory_type_name` is a constant. `_registry` is not.

**Comment by arichar6** [comment]
> Does anyone know whether the class attributes in `Diagnostics` are documented in a different section as the instance attributes in the dunder init?

Good question. Does the `numpydoc` spec have anything to say about class attributes? I would think they should be documented in the class docstring.

**Comment by gracetangg** [comment]
@GarethTMorgan @carolinegsun should we all have the same description of `_factory_type_name` and `_registery` so that way it's consistent

**Comment by arichar6** [comment]
> @GarethTMorgan @carolinegsun should we all have the same description of `_factory_type_name` and `_registery` so that way it's consistent

Yes you should. Good idea 😄

**Comment by GarethTMorgan** [comment]
Here's what I wrote up just now for both: 
`_factory_type_name: str
        Type of DynamicFactory subclass
    _registry: dict
        Allows for :class:'Diagnostic' to be logged in the DynamicFactory registry`

What have y'all written for the two attributes? I don't know if I like my _factory_type_name description.

**Comment by gracetangg** [comment]
i did
`Base DynamicFactory type` for `_factory_type_name:` and `Registered derived ComputeTool classes` for `_registery`

**Comment by carolinegsun** [comment]
I did Grace's for `_registery`, and your initial `_factory_type_name ()`, so `Type of PhysicsModule child class`.

**Comment by GarethTMorgan** [comment]
Let's do Grace's _registry and Caroline's _factory_type_name. Those are both succinct and easily readable.

**Comment by gracetangg** [comment]
Oops I think mine was already merged, can anyone edit mine in the ComputeTools for me so we don't need to open another PR. 😳

**Comment by carolinegsun** [comment]
Will do right now!

**Comment by gracetangg** [comment]
Thank you!!

**Comment by carolinegsun** [comment]
@GarethTMorgan I was editing the file and it got merged, can do you do it for me? Yikes, sorry!

**Comment by carolinegsun** [comment]
I'll just open a new PR and fix it.

**Comment by arichar6** [comment]
Oh no! Sorry about merging everything too fast 😬  My bad.

**Comment by carolinegsun** [comment]
My fault! I didn't put it back in draft mode, sorry.

**Comment by GarethTMorgan** [comment]
oof, no worries. What exactly needs to be done?

**Comment by carolinegsun** [comment]
All good now! I just opened a separate PR to fix it :relaxed:

**Comment by gracetangg** [comment]
I'm going to close the issue since we're done :)
