### ISSUE TITLE
Should we add explicit documentation about self.E[:] vs xarray vs etc methods? 

### ISSUE THREAD

**Issue by littlewatkins** [NRL-Plasma-Physics-Division/turbopy#80]
**Question**
In some of the turbopy modules/apps, @arichar6 uses `self.E[:]` to change the numpy array value that points to the specific object id. 

*Should that have a explicit documentation explaining why that's used and how you could use other methods like xarray or create your own? Or would it be better to just include a comment next to those `[:]` cases?*

My thought is if @Swanekamp has to ask about it, then others will also have questions about it (like me because I didn't remember what that did in python).

**Comment by arichar6** [comment]
I do think that some documentation about this should go somewhere. Right now, it is discussed in the turboPy paper. I think it's worth at least a comment within the example app right now.

In the future, I'd like to have an example of a test which checks that the `id` of a shared object does not change after a call to `update`.

**Comment by arichar6** [comment]
I've created a [new issue](https://github.com/NRL-Plasma-Physics-Division/particle-in-field/issues/10) in the example app.
