### ISSUE TITLE
Automatically share "public" attributes of PhysicsModules?

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#85]
**Discussion Topic**: new method for sharing data between PhysicsModules

It might be interesting to think about alternative ways to share data between PhysicsModules. In particular, there's quite a bit of "boilerplate" code that needs to be written to both "share" and "accept" variables that a developer wants their PhysicsModule to share.

So here's a thought. Maybe we can use “public” and “private” attributes for turboPy. Any attribute (maybe also method?) of a custom PhysicsModule subclass could be automatically shared.  I.e. anything not starting with an underscore would be made available to other PhysicsModules. E.g., a var named “electric_field” would be shared, but one named “_electric_field” would not.

This would probably have to be done in conjunction with a rewrite of the "sharing" algorithm that turboPy is currently using.

**Comment by gracetangg** [comment]
@arichar6 Would this just be a rewrite of exchange_resources and inspect_resources to have a default value, and then automatically calling them before Simulation does?

**Comment by arichar6** [comment]
I think this could be achieved by an implementation of `PhysicsModule.exchange_resources`. At least to start, I'd leave implementation of `inspect_resource` up to the authors of the specific derived `PhysicsModules`. If you want to take a stab at implementing this in a separate branch, I can give you feedback there. 

We should have some sort of naming scheme... maybe `class_name:variable_name`, or something like that. 

Glad to see you are thinking about this. I think it could be a really nice usability upgrade in a future '2.0' release of turboPy.

**Comment by gracetangg** [comment]
I made a small change to `exchange_resources`, but I don't think I have the power to add a branch to the repo.

**Comment by arichar6** [comment]
You can just make the branch in your own repo, and do a PR to `main` as normal. I still need to figure out if I want to have a second "development" branch in the main repo for new features like this. There are pros and cons to that approach.
