### ISSUE TITLE
Create integration test based on block-on-spring example app

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#86]
As described in #35, we are going to be using simple turboPy apps as integration tests. 

The [block-on-spring example app](https://github.com/NRL-Plasma-Physics-Division/block-on-spring) would be a nice one to use for an integration test.

ToDo:
- [ ] Use "block_on_spring" as the fixture "long_name" and "bos" as the "short_name"
- [ ] Save 'good' outputs in tests/fixtures in a sub-folder using the "block_on_spring" name
- [ ] At a minimum, create at least one fixture (bos_run) to run the app and generate output for comparison to 'good' output

**Comment by gracetangg** [comment]
Would it be alright if I changed the ForwardEuler to BlockFowardEuler and ParticleForwardEuler to fix the registry issue?

**Comment by arichar6** [comment]
Do you mean that you get an error trying to register "ForwardEuler" as a compute tool? If so, then yes, it makes sense to call it something like "BlockForwardEuler" instead. I don't think there's any need to change the name of the other compute tool.

**Comment by arichar6** [comment]
Closed with PR #88 

Thanks @gracetangg 🎉
