### ISSUE TITLE
Create a check for test coverage

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#92]
So, I'm only just learning how to check test coverage, but I think this is something we should do for our tests of turboPy. See #14 

We need to:

- [x] Figure out how to calculate test coverage (`pytest --cov`?)
- [x] Integrate this check into the CI pipeline
- [x] Add a coverage badge to the readme

**Comment by arichar6** [comment]
#93 will address the first two items on the ToDo list.

**Comment by arichar6** [comment]
#94 will address the third item on the ToDo by adding a coverage badge

**Comment by padamson** [comment]
Cool
