### ISSUE TITLE
Add test of FieldDiagnostic

### ISSUE THREAD

**Issue by arichar6** [NRL-Plasma-Physics-Division/turbopy#96]
The main thing left in diagnostics.py that is not tested yet is the FieldDiagnostic class. It might be possible to add this to one of the integration tests, and then have better coverage because of that.

See #14

**Comment by AOstenfeld** [comment]
Is there already a test file for diagnostics.py?

**Comment by arichar6** [comment]
I don't think there is

**Comment by AOstenfeld** [comment]
What is the field attribute supposed to do and how do I use it in the do_diagnostic method?

**Comment by arichar6** [comment]
The field attribute saves a reference to data shared by a PhysicsModule. The particle-in-field example uses the FieldDiagnostic, at least in older versions of the code. I think that [this commit](https://github.com/NRL-Plasma-Physics-Division/particle-in-field/tree/66bef34e6ceea2dc67a91ad7318b315c871bf37f) still uses the FieldDiagnostic class from turboPy.

The field attribute is used in `do_diagnostic` to "get" data from the PhysicsModule. Since it points to a numpy array which is updated at every time step, the value changes and the new value can be accessed in `do_diagnostic` through the saved reference `self.field`.

**Comment by AOstenfeld** [comment]
So does the "resource" dictionary come from the PhysicsModule? My main issue is that I don't know what data the field attribute is supposed to hold, so I don't know how to integrate it into the tests.

**Comment by arichar6** [comment]
Got it. The `resource` dictionary is part of the implementation of how turboPy shares data objects between models. For example (again from the particle-in-field app), the EMWave module shares the `self.E` array on [this line](https://github.com/NRL-Plasma-Physics-Division/particle-in-field/blob/8f322f4fad4a5017b10e21fc1858a29ba0c330a0/particle_in_field.py#L35)
```python
        self.publish_resource({"EMField:E": self.E})
```
That dictionary `{"EMField:E": self.E}` is the one that the diagnostic module sees as `resource`. Does that help?

**Comment by arichar6** [comment]
Closed with #108
